/**
 * ProfilePhoto
 * Responsive <picture> for the profile photo: AVIF → WebP → JPEG, two widths.
 * Files are generated by scripts/generate-images.py (3:4 crop, 480w + 704w).
 *
 * Props:
 *  sizes    – the rendered width hint for the browser (CSS sizes syntax)
 *  priority – true for the above-the-fold hero (eager + high fetch priority)
 *  style    – extra inline styles for the <img> (object-position, filter, height…)
 */
const WIDTHS = [480, 704]
const srcSet = (ext) => WIDTHS.map(w => `/img/me-${w}.${ext} ${w}w`).join(', ')

export default function ProfilePhoto({ alt, sizes, priority = false, style }) {
  return (
    <picture>
      <source type="image/avif" srcSet={srcSet('avif')} sizes={sizes} />
      <source type="image/webp" srcSet={srcSet('webp')} sizes={sizes} />
      <img
        src="/img/me-480.jpg"
        srcSet={srcSet('jpg')}
        sizes={sizes}
        alt={alt}
        width={480}
        height={640}
        loading={priority ? 'eager' : 'lazy'}
        fetchPriority={priority ? 'high' : 'auto'}
        decoding={priority ? 'sync' : 'async'}
        style={{ width: '100%', height: '100%', objectFit: 'cover', display: 'block', ...style }}
      />
    </picture>
  )
}
